### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by dweldon** [pdaether/file-cleaner#1]
- `whitList` should be `whiteList`
- The docs use the example `'* */15 * * * *'`, but I think you mean `'00 */15 * * * *'`. The former seems to run every second during minutes which are divisible by 15, while the latter runs once every 15 minutes.

**Comment by pdaether** [comment]
@dweldon Thank you!

**Comment by jeffbyrnes** [comment]
@pdaether clearly it’s been incorrect for some time, but the [docs on npmjs.com](https://www.npmjs.com/package/cron-file-cleaner) still have these typos. Perhaps it would be nice to publish a bug fix to update them? I was nearly caught by the `whitList` typo.
